#!/bin/bash
#
# Services autoshutdown before other other ec2 instance runs mysql
#
while true; do
    for flag in `find /mnt/mailserver -maxdepth 1 -type f -regextype posix-extended -regex '.*flag-ec2id-.*' -printf '%f\n'`
    do
        if [ "$flag" != "flag-ec2id-{instanceid}" ];  then
            systemctl stop mysql
            systemctl stop postfix dovecot httpd opendkim php-fpm
            exit 0
        fi
    done
    sleep 15
done
